apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  volumes:
  - name: ebs-static
    persistentVolumeClaim:
      claimName: ebs-static
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-static
      mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service 
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static-demo
    project: roboshop          
  ports:
  - port: 80
    targetPort: 80