apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: test
    project: dummy
    owner: "jayachandra"
spec:
  containers:
  - name: web-app
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo-test
  labels:
    environment: test
    project: dummy
    owner: "jay"
spec:
  containers:
  - name: web-app
    image: nginx
    ports:
    - containerPort: 80