apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    project: learning
    environment: test
  annotations: 
    purpose: "This is the manifest file to test resource limit"
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
    resource:
      requests: # soft limit
        memory: "128Mi"
        cpu: "250m"
      limits: # hard limit
        memory: "256Mi"
        cpu: "500m"