apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    envFrom:
      - configMapRef:
          name: environment-config