apiVersion: v1
kind: Service
metadata:
  name: cluster-service-ip
spec:
  selector:
    app: internal-app
  ports:
  - port: 80 #service port
    targetPort: 80 # container port
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: internal-app
spec:
  containers:
  - name: webapp
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
    - containerPort: 80