apiVersion: v1
kind: Pod
metadata:
  name: np-service-pod
  labels:
    app: web
  annotations:
    purpose: nodeport poc.
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: np-service
  labels:
    service-type: nodeport
  annotations:
    purpose: to expose app to node through internet
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80