apiVersion: v1
kind: Service
metadata:
  name: np-service-demo
  labels:
    name: np-service-demo
    project: roboshop
    demo: true
spec:
  type: NodePort
  selector:
    name: np-service-web-app
    project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
---
apiVersion: v1
kind: Service
metadata:
  name: np-service-app
  labels:
    name: np-service-web-app
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx