apiVersion: v1
kind: Pod
metadata:
  name: lb-demo-pod
  labels:
    type: load-balancer
  annotations:
    purpose: to demonstrate load-balancer
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: web
spec:
  type: LoadBalancer
  selector:
    type: load-balancer
  ports:
  - port: 80
    targetPort: 80