apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: web
  annotations:
    purpose: replicaset demo
spec:
  replicas: 2
  template:
    selectors:
      matchLabels:
        app: web
    containers:
    - name: nginx
      image: nginx
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
    ports:
    - containerPort: 80