apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: web
  annotations:
    purpose: this is deployment demo
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        demo: web
      annotations:
        purpose: deployment demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"