apiVersion: v1
kind: Service
metadata:
  name: statefulset-svc
  labels:
    app: web
    project: roboshop
spec:
  clusterIP: None
  selector:
      app: web
      project: roboshop
  ports:
  - port: 80
    targetPort: 80