apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Roboshop
  region: us-east-1

managedNodeGroups:
  - name: Worker
    instanceType: c7i-flex.large
    desiredCapacity: 3
