apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-1

nodeGroups:
  - name: test
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    labels: 
    - role: workers 