apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-duplicate-test
spec:
  volumeName: test-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi