apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
  labels:
    purpose: efs
spec:
  volumes:
  - name: efs-static
    persistentVolumeClaim:
      claimName: efs-claim
  containers:
  - name: efs-web
    image: nginx
    volumeMounts:
    - name: efs-static
      mountPath: /usr/share/nginx/html/
---
apiVersion: v1
kind: Service
metadata:
  name: efs-web-svc
spec:
  type: LoadBalancer
  selector:
    purpose: efs
  ports:
  - port: 80
    targetPort: 80