apiVersion: v1
kind: Pod
metadata:
  name: volume-test
  labels:
    app: web
    purpose: efs-demo
spec:
  volumes:
  - name: efs-dynamic
    persistentVolumeClaim:
      claimName: efs-claim
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-dynamic
      mountPath: /usr/share/nginx/html/
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: demo-app
spec:
  type: LoadBalancer
  selector:
    app: web
    purpose: efs-demo
  ports:
  - port: 80
    targetPort: 80    